# Base configs
baseurl: "https://imogengunther.github.io"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Photography by Imogen Gunther"
subtitle: "My portfolio"
author: "Imogen Gunther"
header:
 title: "Photography"
 subtitle: "by Imogen Gunther"
footer:
 name: "Hey there, my name is Imogen"
 bio: ""
 github: ""
web_design: "AJ"
social_urls:
  # `facebook
  # twitter: "https://www.twitter.com/ram__patra"
  # instagram: "https://www.instagram.com/ram_patra"
  # dribbble: "https://dribbble.com/rampatra"
  # linkedin: "https://in.linkedin.com/in/ram-patra"
  # github: "https://www.github.com/rampatra"
